    server {
        listen       80;
        server_name localhost;

        root /app/;
        index index.php index.html;

        location / {
            try_files $uri $uri/ -404;
        }
	location /Lab1/ {
	    root /src/Lab1;
	    index index.php;
	}

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        }

    }
